/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d1dbec",
        "on-secondary-fixed": "#341100",
        "on-secondary-fixed-variant": "#783200",
        "primary-fixed-dim": "#95d4b3",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eef4ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-surface-variant": "#404943",
        "on-tertiary-fixed-variant": "#76330d",
        "outline": "#707973",
        "on-error-container": "#93000a",
        "primary-container": "#2d6a4f",
        "error": "#ba1a1a",
        "surface-tint": "#2c694e",
        "tertiary-fixed": "#ffdbcc",
        "surface": "#f8f9ff",
        "inverse-primary": "#95d4b3",
        "on-tertiary-container": "#ffd0bb",
        "on-primary-container": "#a8e7c5",
        "primary-fixed": "#b1f0ce",
        "on-surface": "#121c28",
        "secondary-fixed-dim": "#ffb690",
        "on-primary-fixed": "#002114",
        "on-secondary-container": "#5c2400",
        "secondary-container": "#fd761a",
        "surface-container": "#e5eeff",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "tertiary": "#77340e",
        "on-primary-fixed-variant": "#0e5138",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary": "#9d4300",
        "on-tertiary-fixed": "#351000",
        "secondary-fixed": "#ffdbca",
        "on-secondary": "#ffffff",
        "outline-variant": "#bfc9c1",
        "tertiary-fixed-dim": "#ffb693",
        "surface-container-highest": "#d9e3f4",
        "tertiary-container": "#954b24",
        "inverse-surface": "#27313e",
        "primary": "#0f5238",
        "on-background": "#121c28",
        "surface-container-high": "#dfe9fa",
        "surface-variant": "#d9e3f4",
        "surface-bright": "#f8f9ff"
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "xl": "40px",
        "md": "16px",
        "base": "4px",
        "margin-desktop": "64px",
        "lg": "24px",
        "xs": "4px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "label-xs": ["Work Sans", "Inter", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "label-sm": ["Work Sans", "Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-xs": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
};